// Generated by https://quicktype.io

export interface IIssue {
  title:             string[];
  description:       string[];
  impact:            string[];
  remediation:       string[];
  cvss_vector:       string[];
  other_refs:        string[];
  technical_details: string[];
  current_status:    string[];
}
